# -*- coding: utf-8 -*-
# Generated by Django 1.10.7 on 2017-09-01 23:57
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Article',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('headline', models.CharField(max_length=255)),
                ('description', models.CharField(max_length=255)),
                ('src', models.CharField(max_length=255)),
                ('domain', models.CharField(max_length=255)),
                ('datepub', models.DateField()),
            ],
        ),
    ]
